POST http://localhost:3000/add

content-type: application/json

{
    "title": "Rambo"
}

###
POST http://localhost:3000/login

content-type: application/json

{
    "username": "maxmaxmax",
    "password": "maxmaxmax"
}